#!/usr/bin/env bash

livecd() {
	# Creates a LiveCD using GRUB's mkrescue tool. The 'iso' folder is turned into the root disk, you can simply install packages/copy files to it.
	rm -Rf RELEASE
	mkdir -p iso/boot/grub RELEASE

	sh hal/boot/grub-2.12/pkgbuild.sh install

	cp hal/boot/grub-2.12/grub.cfg iso/boot/grub/
	iso/bin/grub-mkrescue -o RELEASE/chimera.iso iso
	rm -Rf iso
}

all() {
	echo "Building all..."
	sh hal/boot/grub-2.12/pkgbuild.sh build
}

clean() {
	sh hal/boot/grub-2.12/pkgbuild.sh clean
}

release() {
	livecd
}

"$@"


