#!/usr/bin/env bash

export CHIMERA_SRC_ROOT=$PWD

livecd() {
	# Creates a LiveCD using GRUB's mkrescue tool. 
	# The 'iso' folder is the root of the LiveCD, you can simply install packages/copy files to it.
	rm -Rf RELEASE
	mkdir -p iso/boot/grub RELEASE

	sh hal/boot/grub-2.12/pkgbuild.sh install
	sh hal/i386/initializer/pkgbuild.sh install
	
	# random archive to satisfy grub until we have kernel and servers setup...
	tar -czf iso/boot/chimera.gz hal/boot/grub-2.12/grub.cfg hal/boot/grub-2.12/pkgbuild.sh

	cp hal/boot/grub-2.12/grub.cfg iso/boot/grub/
	iso/bin/grub-mkrescue -o RELEASE/chimera.iso iso
	rm -Rf iso
}

all() {
	echo "Building all..."
	sh hal/boot/grub-2.12/pkgbuild.sh build
	sh hal/i386/initializer/pkgbuild.sh build
}

clean() {
	sh hal/boot/grub-2.12/pkgbuild.sh clean
}

release() {
	livecd
}


"$@"
